export interface Appcontraloria {
    id: string;
    dispositivo: string;
    modelo: string; 
    serial: string; 
    placa: string;
    bienes_nacionales: string;
    cedula: string;
    usuario: string;
    Departamento: string;
    os: string;
    cpu: string; 
    memoria: string;
    almacenamiento: string;
    mantenimiento: string;
    tamaño: string;
    tipo_de_mantenimiento: string;
    fecha_de_mantenimiento: string;
    limpieza: string;
    defragmentacion: string;
    fecha_de_entrada: string;
    fecha_de_asignacion: string;
    fecha_de_actualizacion: string;
    fecha_de_elimusuario: string;
    fecha_de_borrados: string;
    fecha_de_reingreso: string;
    fecha_de_descargoBN: string;
    email: string;
    comentarioeli:string;
    comentarioeliusuario:string;
    fechacorreoenviode: string;
    comentarioreingresoDE: string;
    comentariodescargoAlma:string;
}
